version: '3.4'

services:
  DayRateService:
    image: ${DOCKER_REGISTRY-}DayRateService
    container_name: DayRateServiceContainer
    build:
      context: .
      dockerfile: DayRateService/Dockerfile
    environment: 
      - ASPNETCORE_ENVIORNMENT=Development
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets.ro
      - ${APPDATA}/ASP.NET/HTTPS:/root/.aspnet/https:ro

  DayRateService1:
    image: ${DOCKER_REGISTRY-}DayRateService
    container_name: DayRateServiceContainer1
    build:
      context: .
      dockerfile: DayRateService/Dockerfile
    environment: 
      - ASPNETCORE_ENVIORNMENT=Development
    ports:
      - "6000:80"
      - "6001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets.ro
      - ${APPDATA}/ASP.NET/HTTPS:/root/.aspnet/https:ro

  WeekPayModelService:
    image: ${DOCKER_REGISTRY-}WeekPayModelService
    container_name: WeekPayModelServiceContainer
    build:
      context: .
      dockerfile: WeekPayModelService/Dockerfile

  TimeIntervalService:
    image: ${DOCKER_REGISTRY-}TimeIntervalService
    container_name: TimeIntervalServiceContainer
    build:
      context: .
      dockerfile: TimeIntervalService/Dockerfile
